`// # Query for all users
query {
  users {
    id
    name
  }
}

// # Query a single user by their id
query {
  user(id: "user-1") {
    id
    name
  }
}

// # Create a new user
mutation {
  createUser(name: "Bob") {
    id
    name
  }
}`


// inserts data, fed in as parameters (which will become args), and will return the id that was autogenerated afterward
`mutation {
    post(description:"BS", url: "photobucket.com"){
      id
    }
}`

// updates data of a link somewhere
`mutation {
    updateLink(id:"link-0", description:"POTATOFCKBOI", url:"facebook.com"){
      id
      description
      url
    }
  }`